---
apiVersion: 1

datasources:
  - name: "Loki"
    type: "loki"
    uid: "loki"
    access: "proxy"
    isDefault: false
    editable: false
    version: 1
    url: "http://loki:3100/"
    jsonData:
      maxLines: 1000
      timeout: 60
      derivedFields:
        - datasourceUid: "tempo"
          matcherRegex: "trace_id=(\\w+)"
          name: "TraceID"
          url: "$${__value.raw}"
          urlDisplayLabel: "View Trace"
        - datasourceUid: "tempo"
          matcherRegex: '"trace_id":"([0-9a-fA-F]{32})"'
          name: "TraceID"
          url: "$${__value.raw}"
          urlDisplayLabel: "View Trace"
        - datasourceUid: "tempo"
          matcherRegex: '"fields":\\{[^}]*"trace_id":"([0-9a-fA-F]{32})"'
          name: "TraceID"
          url: "$${__value.raw}"
          urlDisplayLabel: "View Trace"
