---
apiVersion: 1

datasources:
  - name: "Prometheus"
    type: "prometheus"
    uid: "prometheus"
    access: "proxy"
    isDefault: true
    editable: false
    version: 1
    url: "http://prometheus:9090/"
    jsonData:
      httpMethod: "POST"
      prometheusType: "Prometheus"
      exemplarTraceIdDestinations:
        - name: "trace_id"
          datasourceUid: "tempo"
          urlDisplayLabel: "View Trace"
