---
apiVersion: 1
datasources:
  - name: "Tempo"
    type: "tempo"
    uid: "tempo"
    access: "proxy"
    isDefault: false
    editable: false
    version: 1
    url: "http://tempo:3200/"
    jsonData:
      search:
        hide: false
      tracesToLogs:
        datasourceUid: "loki"
        filterByTraceID: true
        filterBySpanID: false
        spanStartTimeShift: "-5m"
        spanEndTimeShift: "5m"
        mapTagNamesEnabled: true
      tracesToMetrics:
        datasourceUid: "prometheus"
      tracesToMetricsV2:
        datasourceUid: "prometheus"
      serviceMap:
        datasourceUid: "prometheus"
      nodeGraph:
        enabled: true
      lokiSearch:
        datasourceUid: "loki"
      spanBar:
        type: "Duration"
      streaming: false
      timeout: "30"
