services:
  traefik:
    image: "traefik:v3.4.4"
    restart: "always"
    security_opt:
      - "no-new-privileges:true"
    ports:
      - "80:80"
    volumes:
      - "./config/traefik/:/etc/traefik/:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - "local-stack-vnet"
    labels:
      traefik.enable: true

      traefik.http.routers.traefik-dashboard.rule: "Host(`traefik.docker.localhost`) && PathPrefix(`/`)"
      traefik.http.routers.traefik-dashboard.entrypoints: "http"
      traefik.http.routers.traefik-dashboard.service: "dashboard@internal"
      traefik.http.routers.traefik-dashboard.middlewares: "dashboard_redirect@internal,dashboard_stripprefix@internal"

      traefik.http.routers.traefik-api.rule: "Host(`traefik.docker.localhost`) && PathPrefix(`/api`)"
      traefik.http.routers.traefik-api.entrypoints: "http"
      traefik.http.routers.traefik-api.service: "api@internal"

networks:
  local-stack-vnet:
    name: "local-stack-vnet"
  local-stack-private-vnet:
    name: "local-stack-private-vnet"
    internal: true

volumes:
  local-stack-prometheus-data:
    name: "local-stack-prometheus-data"
  local-stack-loki-data:
    name: "local-stack-loki-data"
  local-stack-tempo-data:
    name: "local-stack-tempo-data"
