services:
  traefik:
    image: "traefik:v3.4.4"
    restart: "always"
    security_opt:
      - "no-new-privileges:true"
    ports:
      - "80:80"
    volumes:
      - "./config/traefik/:/etc/traefik/:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    networks:
      - "local-stack-vnet"
    labels:
      traefik.enable: true

      traefik.http.routers.traefik-dashboard.rule: "Host(`traefik.docker.localhost`) && PathPrefix(`/`)"
      traefik.http.routers.traefik-dashboard.entrypoints: "http"
      traefik.http.routers.traefik-dashboard.service: "dashboard@internal"
      traefik.http.routers.traefik-dashboard.middlewares: "dashboard_redirect@internal,dashboard_stripprefix@internal"

      traefik.http.routers.traefik-api.rule: "Host(`traefik.docker.localhost`) && PathPrefix(`/api`)"
      traefik.http.routers.traefik-api.entrypoints: "http"
      traefik.http.routers.traefik-api.service: "api@internal"

  prometheus:
    image: "prom/prometheus:v3.6.0"
    restart: "always"
    command:
      - "--config.file=/etc/prometheus/prometheus.yaml"
      - "--storage.tsdb.path=/data"
      - "--storage.tsdb.retention.time=7d"
      - "--storage.tsdb.retention.size=10GB"
      - "--web.enable-remote-write-receiver"
    volumes:
      - "./config/prometheus/:/etc/prometheus/:ro"
      - "local-stack-prometheus-data:/data/"
    networks:
      - "local-stack-private-vnet"

  loki:
    image: "grafana/loki:3.5"
    restart: "always"
    volumes:
      - "./config/loki/:/etc/loki/:ro"
      - "local-stack-loki-data:/data/"
    networks:
      - "local-stack-private-vnet"

  tempo:
    image: "grafana/tempo:2.8.2"
    restart: "always"
    user: "root"
    command: ["-config.file=/etc/tempo/tempo.yaml"]
    volumes:
      - "./config/tempo/:/etc/tempo/:ro"
      - "local-stack-tempo-data:/data/"
    networks:
      - "local-stack-private-vnet"

networks:
  local-stack-vnet:
    name: "local-stack-vnet"
  local-stack-private-vnet:
    name: "local-stack-private-vnet"
    internal: true

volumes:
  local-stack-prometheus-data:
    name: "local-stack-prometheus-data"
  local-stack-loki-data:
    name: "local-stack-loki-data"
  local-stack-tempo-data:
    name: "local-stack-tempo-data"
